variables:
#  GIT_STRATEGY: fetch
    CI_SCRATCH: /home/xl_ci/ci_scratch


before_script:
    - module load common

stages:
    - release
    - deploy

deploy_doc:
    stage: release
    retry: 1
    only:
        refs:
          - master
        changes:
          - doc/source/**/**/**/**/*
    artifacts:
        name: "nuclei_board_labs_doc-${CI_COMMIT_SHA::8}"
        paths:
            - doc/build
        expire_in: 2 day
    script:
        - cd doc
        - pip3 install --user -r requirements.txt
        - export PATH=$HOME/.local/bin:$PATH
        - make clean
        - make all
        - ssh xl01 "rm -rf /home/xl_ci/doc_center/nuclei_board_labs/*"
        - ssh xl01 "mkdir -p /home/xl_ci/doc_center/nuclei_board_labs/"
        - cd build
        - scp -r html xl01:/home/xl_ci/doc_center/nuclei_board_labs
        - cd ..
          #- make linkcheck
        - make latexpdf
        - cp build/latex/*.pdf build/html/
    tags:
        - software-server

deploy_website:
    stage: deploy
    when: on_success
    only:
        refs:
          - master
        changes:
          - doc/source/**/**/**/**/*
    retry: 1
    script:
        - ./.ci/ftp_deploy.sh $FTPUSER $FTPPWD $FTPSERVER doc/build/html nuclei_board_labs
    tags:
        - software-server
    dependencies:
        - deploy_doc
